export { default as Header } from "./Header"
export { default as Hero } from "./Hero"
export { default as ProjectItem } from "./small_comps/ProjectItem"
export { default as Section } from "./Section"
export { default as Footer } from "./Footer"
export { default as AnimatedWave } from "./small_comps/AnimatedWave"
export { default as Experience } from "./Experience"
export { default as DownArrow } from "./small_comps/DownArrow"